name: Publish image docker hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: tfbuilder
        uses: actions/
      - name: build
        run: |
          docker build . -t igoralcantara/tfbuilder:0.50
      - name: publish
        run: |
          docker login -u igoralcantara -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push igoralcantara/tfbuilder:0.50
