name: Publish image docker hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build . -t igoralcantara/tfbuilder:0.51
      - name: publish
        run: |
          docker login -u igoralcantara -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push igoralcantara/tfbuilder:0.51